### ISSUE TITLE
Open Presentation Preview in Obsidian first!

### ISSUE THREAD

**Issue by dumojun101** [varunshenoy/GraphGPT#1]
Open Presentation Preview in Obsidian first!
![image](https://user-images.githubusercontent.com/1902028/215942586-1982ee17-a356-45ad-bb43-5f4698bdf760.png)

What does this mean

**Comment by szhu** [comment]
This repo's code doesn't contain the word "Obsidian" at all. You likely have another app running on localhost:3000.
