### ISSUE TITLE
Mistake in prompt on purpose?

### ISSUE THREAD

**Issue by RobFlo98** [varunshenoy/GraphGPT#13]
I just wanted to ask if the wrong double braces "**}}**" in the prompt are intentional? (In line 26)

```
"edges": [
        { "from": 1, "to": 2, "label": "roommate" }},
      ]
```

https://github.com/varunshenoy/GraphGPT/blob/main/public/prompts/main.prompt#L26

**Comment by varunshenoy** [comment]
Fixed in #16. Thanks for the catch!
