### ISSUE TITLE
Optimize prompt length

### ISSUE THREAD

**Issue by ramonwenger** [varunshenoy/GraphGPT#16]
Currently a single request seems to use ~450 tokens on an OpenAI account, which is comprised of the prompt  and the response, for example:

```
313 prompt + 146 completion = 459 tokens
```

This turns out to about 0.01$ per request.

Maybe there are ways to shorten the length of both the prompt and the response, to reduce the token usage a bit.

**Comment by ramonwenger** [comment]
I wrote PR #17 to reduce the prompt complexity, for one approach to optimize the usage.

The [tokenizer](https://platform.openai.com/tokenizer) provided by OpenAI helps with the analysis.

**Comment by varunshenoy** [comment]
Merged. Thanks again!
