### ISSUE TITLE
Deployed to Vercel

### ISSUE THREAD

**Issue by szhu** [varunshenoy/GraphGPT#3]
Hi, found this via HN -- cool project!

I wanted to play around with this over the next few days and didn't want to keep the build server running, so I deployed it* here:

~https://<wbr>graph-gpt.vercel.app/~ (edit: now deleted, see new url in later comments)

I just wanted to create an issue to let you know that if you want to use this Vercel URL (for example as an official demo URL of this project), I'm happy to give it to you -- just let me know here!

\* The only modification I made was to add a prompt that asks for the OpenAI API key and stores it in localStorage. I think the UI for that can definitely be improved, but I just wanted something that was usable without opening devtools for now.

**Comment by varunshenoy** [comment]
Dude, this is awesome. Would love to use this as an official demo URL. Any chance you make a PR with the modification?

**Comment by KyleHaynes** [comment]
Sorry, no value to add here, just that I love seeing issues like this!

**Comment by szhu** [comment]
All right, made https://github.com/varunshenoy/GraphGPT/pull/4

You can merge it as is if you want, but I personally don't think it's a good idea for the official demo link to ask for credentials before showing any info about what it is. I added some suggestions in the PR; I'm not sure if I have time to implement them, but hopefully they're not hard for you to implement.

For transferring the URL to you, I think I just have to delete my deployment right before you attempt to use it. Feel free to DM me on Twitter to coordinate that?

@KyleHaynes love comments like yours too!! appreciate the support 💕

**Comment by szhu** [comment]
Actually, regarding the URL, maybe it should be graphgpt.vercel.app instead? If you prefer that one, it currently looks unclaimed so you can just deploy to there when you have a chance.

I don't have a preference and will delete my deployment afterwards in either case.

**Comment by varunshenoy** [comment]
Yup! That's what I grabbed: [graphgpt.vercel.app](https://graphgpt.vercel.app/). Might have some kinks but I'll take a look at them tomorrow. Thanks so much!

**Comment by eren23** [comment]
This project is fire, thanks a lot for coming up with this @varunshenoy
