### ISSUE TITLE
Wrong error message when having insufficient credits on OpenAI

### ISSUE THREAD

**Issue by ramonwenger** [varunshenoy/GraphGPT#8]
Currently the alert window notifies the user with something along the lines of

```
Error: TypeError: t.choices is undefined. Please double-check your API key.
```

The actual error message from the API is

```
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
```

Credits on OpenAI seem to expire after some time, so the API request fails without having a subscription.

**Comment by ramonwenger** [comment]
I have submitted PR #7 that displays a more helpful message in this case.

**Comment by carlomuna** [comment]
I see that message (Error: TypeError: undefined is not an object (evaluating 't.choices[0]'). Please double-check your API key.) but I have credits on OpenAI. Do you know why I see it?

**Comment by ramonwenger** [comment]
@carlomuna Look at what the console says, and also in the network tab of your dev tools how the response from the OpenAI API says in the response body.
